(function(){
const C={marketing:'שיווק',ads:'פרסום',pr:'יחסי ציבור',sales:'מכירות',branding:'מיתוג',product:'דיוק המוצר'};
const Q=[
{k:'marketing',d:'שיווק',type:'scale',q:'עד כמה ברור לך מה היעד השיווקי המרכזי של העסק שלך?',h:'1 = לא ברור · 10 = ברור ומסודר'},
{k:'branding',d:'מיתוג',type:'scale',q:'כשלקוח חדש פוגש את העסק שלך, עד כמה הוא מבין מיד למה לבחור דווקא בך?',h:'1 = הבידול לא ברור · 10 = הערך ברור מאוד'},
{k:'ads',d:'פרסום',type:'scale',q:'עד כמה הפרסום שלך מייצר פניות או מכירות שאפשר למדוד?',h:'1 = בעיקר חשיפה · 10 = תוצאה מדידה'},
{k:'sales',d:'מכירות',type:'choice',q:'מה קורה בדרך כלל כשנכנסת פנייה טובה?',opts:['יש תהליך מסודר ומעקב עד סגירה','יש תהליך, אבל המעקב חלקי','כל אחד מטפל אחרת','חלק מהפניות פשוט נעלמות']},
{k:'pr',d:'יחסי ציבור',type:'choice',q:'איזו נוכחות יש לעסק שלך מעבר לפרסום הישיר?',opts:['כתבות, המלצות ושיתופי פעולה באופן קבוע','יש מדי פעם חשיפה או המלצות','בעיקר המלצות אישיות','כמעט שאין חשיפה']},
{k:'product',d:'דיוק המוצר',type:'choice',q:'עד כמה ההצעה שלך מדויקת לבעיה שלקוחות באמת מוכנים לשלם כדי לפתור?',opts:['מדויקת מאוד','די מדויקת אבל אפשר לחדד','קשה לי להגדיר למי בדיוק','אני מציע כמה דברים לכמה קהלים']},
{k:'marketing',d:'שיווק',type:'choice',q:'מאיפה מגיעים רוב הלקוחות החדשים שלך?',opts:['המלצות','פרסום','תוכן וקהילה','שיתופי פעולה','אין מקור קבוע']},
{k:'branding',d:'מיתוג',type:'scale',q:'עד כמה האתר, הוואטסאפ, ההצעות והפרסומים משדרים אותה רמה?',h:'1 = לא אחיד · 10 = מותג ברור ואחיד'},
{k:'ads',d:'פרסום',type:'choice',q:'כשאתה מפרסם, עד כמה הקהל שאתה מכוון אליו מוגדר?',opts:['מדויק מאוד','יש כיוון אבל אפשר לדייק','פונה לכמה קהלים','כמעט לכולם']},
{k:'sales',d:'מכירות',type:'scale',q:'אם מחר ייכנסו פי שניים פניות, עד כמה העסק ערוך להפוך אותן להכנסות?',h:'1 = לא ערוך · 10 = תהליך מסודר'}
];
let i=0,answers=[];const $=id=>document.getElementById(id);const track=(n,p)=>{try{if(typeof window.gtag==='function')window.gtag('event',n,p||{})}catch(e){}};
function render(){const q=Q[i];$('hero').style.display='none';$('result').style.display='none';$('quiz').style.display='block';$('count').textContent=`שאלה ${i+1} מתוך ${Q.length}`;$('pct').textContent=Math.round(i/Q.length*100)+'%';$('barfill').style.width=((i+1)/Q.length*100)+'%';$('domain').textContent=q.d;$('question').textContent=q.q;$('hint').textContent=q.h||'';$('scale').innerHTML='';if(q.type==='choice'){q.opts.forEach((t,j)=>{const b=document.createElement('button');b.type='button';b.className='choice'+(answers[i]===j+1?' sel':'');b.textContent=t;b.onclick=()=>pick(j+1);$('scale').appendChild(b)})}else{for(let n=1;n<=10;n++){const b=document.createElement('button');b.type='button';b.className='num'+(answers[i]===n?' sel':'');b.textContent=n;b.onclick=()=>pick(n);$('scale').appendChild(b)}}$('back').style.visibility=i?'visible':'hidden';window.scrollTo({top:0,behavior:'smooth'})}
function pick(n){answers[i]=n;track('quiz_answer',{question_number:i+1,category:Q[i].k,score:n,type:Q[i].type});if(i<Q.length-1){i++;render()}else finish()}
function finish(){const s={},c={};Q.forEach((q,j)=>{const n=answers[j]||0;s[q.k]=(s[q.k]||0)+n;c[q.k]=(c[q.k]||0)+1});const pct={};Object.keys(C).forEach(k=>pct[k]=c[k]?Math.round(s[k]/(c[k]*10)*100):0);const keys=Object.keys(C).sort((a,b)=>pct[a]-pct[b]);const gap=keys[0];$('quiz').style.display='none';$('result').style.display='block';$('rt').textContent=C[gap];$('rx').textContent='הצורך המרכזי בעסק';const order=['marketing','ads','pr','sales','branding','product'];order.forEach((k,n)=>{$('m'+(n+1)).style.width=pct[k]+'%';$('v'+(n+1)).textContent=pct[k]+'%'});$('rr').textContent='';$('rn').textContent='';$('nextText').textContent='';$('wa').href='https://wa.me/972553048242?text='+encodeURIComponent('היי יוסי, השלמתי את האבחון. הצורך המרכזי שעלה לי הוא '+C[gap]+'.');track('quiz_complete',{diagnosis:gap,questions_answered:Q.length});window.scrollTo({top:0,behavior:'smooth'})}
window.start=()=>{i=0;answers=[];track('quiz_start');render()};window.goBack=()=>{if(i>0){i--;render()}};window.restart=()=>{i=0;answers=[];$('quiz').style.display='none';$('result').style.display='none';$('hero').style.display='block'};track('quiz_page_open');
})();